# Generated by Django 6.0.7 on 2026-07-28 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='favoritos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreFavorito', models.CharField(max_length=100)),
                ('descripcionFavorito', models.CharField(max_length=255)),
            ],
        ),
    ]
