# Generated by Django 6.0.7 on 2026-07-31 18:29

from django.db import migrations, models


def crear_generos_iniciales(apps, schema_editor):
    Genero = apps.get_model('PixelStrike', 'Genero')
    nombres = [
        'Juegos de rol',
        'Simulación y vida',
        'Acción-aventura',
        'Terror y sigilo',
        'Juegos de ritmo',
    ]
    for orden, nombre in enumerate(nombres, start=1):
        Genero.objects.get_or_create(
            nombre=nombre,
            defaults={'orden': orden, 'activo': True},
        )


class Migration(migrations.Migration):

    dependencies = [
        ('PixelStrike', '0002_juego_noticia_alter_favoritos_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.RunPython(
            crear_generos_iniciales,
            migrations.RunPython.noop,
        ),
    ]
