# Generated by Django 6.0.7 on 2026-08-02 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PixelStrike', '0003_genero'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Juego',
        ),
    ]
