# Generated by Django 6.0.7 on 2026-08-04 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PixelStrike', '0004_delete_juego'),
    ]

    operations = [
        migrations.CreateModel(
            name='resennas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreResena', models.CharField(max_length=100)),
                ('descripcionResena', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Noticia',
        ),
    ]
