# Generated by Django 6.0.7 on 2026-08-04 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PixelStrike', '0005_resennas_delete_noticia'),
    ]

    operations = [
        migrations.DeleteModel(
            name='resennas',
        ),
        migrations.AlterModelOptions(
            name='favoritos',
            options={},
        ),
    ]
